### ISSUE TITLE
aumentar o tamanho da caixa de texto

### ISSUE THREAD

**Issue by delki8** [fernandohbb/fernandohbb.github.io#1]
- [x] aumentar o tamanho da caixa de texto
- [x] colocar o botao embaixo da caixa de texto

![image](https://user-images.githubusercontent.com/2289068/164109232-f9d5b3cc-d587-49dc-ab36-747d9b984eba.png)

**Comment by fernandohbb** [comment]
Que mais😲🤥👨‍💻

Em ter, 19 de abr de 2022 19:04, Ruither Borba ***@***.***>
escreveu:

**Comment by delki8** [comment]
feito :) :+1:
